static int fix_client_session(struct fix_session_cfg *cfg);
static unsigned long fix_quoterequest_fields(struct fix_session *session, struct fix_field *fields, struct fix_quoterequest *quoterequest);
static int fix_quote_request(struct fix_session *session, struct fix_field *fields, long nr_fields);
static int fix_message_reject(struct fix_message *msg);
static int fix_quote_ack(struct fix_session *session, struct fix_message *msg);
static int fix_quote(struct fix_session *session, struct fix_message *msg);
static int fix_execution_report(struct fix_session *session, struct fix_message *msg);
//static inline struct fix_field *fix_field_by_tag(struct fix_message *msg, enum fix_tag tag);
//static int store_quote_ack(struct fix_session *session, struct fix_quoteack *quoteack);
//static int store_quote(struct fix_session *session, struct fix_quote *quote);
//static int test_store_quote_ack();
//static int test_store_quote();
static int send_quote_ack(struct fix_session *session, struct fix_quoteack *quoteack);
static int send_quote(struct fix_session *session, struct fix_quote *quote);
static int send_execution_report(struct fix_session *session, struct fix_executionreport *executionreport);
int load_scripts();
static unsigned long fix_new_order_single_fields(struct fix_session *session, struct fix_field *fields, struct fix_order *order);
static void check_for_data();
